matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install -U setuptools==45
        - pip install -r neuroscout/requirements.txt
        - pip install -e git+https://github.com/PsychoinformaticsLab/pliers.git#egg=pliers
        - pip install pytest-cov
      script:
        - python -m pytest neuroscout/tests/ --cov=./
        # cd frontend && npm test
      env:
      - APP_SETTINGS=neuroscout.config.app.TravisConfig PYTHONHASHSEED=0
      addons:
        postgresql: "9.4"
      before_script:
        - cp neuroscout/config/example_app.py neuroscout/config/app.py
        - cp neuroscout/frontend/src/config.ts.example neuroscout/frontend/src/config.ts
        - psql -c 'create database travis_ci_test;' -U postgres
        # CI=""; cd neuroscout/frontend && yarn install --ignore-engines --concurrency=1 && yarn build --concurrency=1
        - CI="true"
        - python -m pliers.support.download
      before_install:
        - sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
        - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        - sudo apt-get -qq update
        - sudo apt-get install -yq git-annex-standalone tesseract-ocr

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      node_js:
        - "lts/*"
      addons:
      apt:
        packages:
        - libgconf-2-4
      cache:
        yarn: true
        directories:
          - ~/node_modules
        override:
          - npm ci
          - npm run cy:verify
          - npm run cy:info
      install:
        - cd ./neuroscout/frontend
        - yarn install
        - npm install -g wait-on
      script:
        - mv ./src/config.ts.example ./src/config.ts
        - mv cypress-test.json cypress.json
        - yarn start & wait-on http://localhost:3000/
        - npm run cy:run
