version: "2"
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - /usr/src/app/static
      - migrations:/migrations
      # ADD OTHERS VOLUMES HERE
    command: /usr/local/bin/gunicorn -w 2 -b :8000 core:app --log-level debu
    environment:
      - APP_SETTINGS=config.DevelopmentConfig

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=neuroscout

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - "API_URL=http://localhost/swagger/"
    ports:
      - '5000:8080'

  redis:
    image: redis

  worker:
    build:
      context: ./celery
      dockerfile: Dockerfile
    depends_on:
      - redis

  monitor:
    build:
      context: ./celery
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  migrations:
