web:
  restart: always
  build: ./web
  ports:
    - 80:80
  expose:
    - 80
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  command: python app.py
  environment:
    - APP_SETTINGS=config.DevelopmentConfig

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"