version: "2"
services:
  neuroscout:
    restart: always
    build: ./neuroscout
    expose:
      - "8000"
    volumes:
      - ./postgres/migrations:/migrations
      - ./:/neuroscout
      - ${DATASET_DIR}:/datasets
      - ${KEY_DIR}:/keys
      - ${FILE_DATA}:/file-data
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neuroscout.core:app --log-level debug --timeout 120
    env_file:
      - .env
      - .pliersenv 
    container_name: neuroscout

  nginx:
    restart: always
    build: ./nginx
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=neuroscout.org,www.neuroscout.org
      - LETSENCRYPT_HOST=neuroscout.org,www.neuroscout.org
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - neuroscout

  postgres:
    restart: always
    build: ./postgres
    shm_size: 1g
    volumes:
      - /media/neuroscout-db/db_data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=neuroscout
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
      - .pliersenv

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - "API_URL=https://neuroscout.org/swagger/"
    expose:
      - '8080'

  redis:
    image: redis

  worker:
    build:
      context: ./
      dockerfile: celery_worker/Dockerfile
    depends_on:
      - redis
    entrypoint: celery -A tasks worker --loglevel=info
    volumes:
      - ${FILE_DATA}:/file-data
      - ${DATASET_DIR}:/datasets
      - ./celery_worker:/celery_worker
    env_file:
      - .env

  monitor:
    build:
      context: ./
      dockerfile: celery_worker/Dockerfile
    ports:
     - "5555:5555"
    entrypoint: celery -A tasks flower --auth="aleph4@gmail.com|rosswilsonblair@gmail.com|rbrrcc@gmail.com" --url-prefix=flower
    volumes:
      - ./celery_worker:/celery_worker
    depends_on:
      - redis
    env_file:
       - .env

#volumes:
#  certs:
#  certs-data:

networks:
  default:
    external:
      name: nginx-proxy
