site_name: Neuroscout Docs
site_author: Alejandro de la Vega
site_url: https://neuroscout.github.io/neuroscout/
nav:
    - Home: index.md
    - Analysis Tutorial:
      - Getting started: builder/index.md
      - Predictors: builder/predictors.md
      - Transformations: builder/transformations.md
      - HRF Convolution: builder/hrf.md
      - Contrasts: builder/contrasts.md
      - Review: builder/review.md
      - Run / Status: builder/run.md
      - Bibliography: builder/bib.md
    - Browse & manage:
      - Browse: browse/index.md
      - Clone: browse/clone.md
    - Run analyses:
      - Introduction: cli/index.md
      - Docker: cli/docker.md
      - Singularity: cli/singularity.md
      - General Usage: cli/usage.md
    - FAQ: faq.md

theme: material
markdown_extensions:
  - admonition
