site_name: Neuroscout Docs
site_author: Alejandro de la Vega
site_url: https://neuroscout.github.io/neuroscout/
nav:
    - Home: index.md
    - Building analyses:
      - Getting started: builder/index.md
      - Predictors: builder/predictors.md
      - Transformations: builder/transformations.md
      - HRF: builder/hrf.md
      - Contrasts: builder/contrasts.md
      - Review: builder/review.md
      - Run / Status: builder/run.md
      - Bibliography: builder/bib.md

    - Running analyses:
      - Introduction: cli/index.md
    - FAQ: faq.md

theme: readthedocs
markdown_extensions:
  - admonition
