studyforrest_phase2:
  path: /datasets/studyforrest-data-phase2/
  dataset_address: https://github.com/adelavega/studyforrest-data-phase2.git
  tasks:
    objectcategories:
      features:
        - default.json
      filters:
        subject: "0[1-2]"
        run: 1
