studyforrest_phase2:
  path: /datasets/studyforrest-data-phase2/
  tasks:
    movie:
      filters:
        subject: "01"
        run: 1
        session: "movie"
      features:
        - movie.json
      parameters:
        skip_predictors: True
